
spring:
  application:
    name: storage-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:storage}

  liquibase:
    change-log: classpath:migrations/changelog-master.xml

server.port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

keycloak:
  authServerUrl: http://localhost:8080
  realm: first_realm
  resource: my_app
  credentials:
    secret: bwC7rAnMseP86rXS65Yw8WVMHd79izCx