spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB

config:
  aws:
    region: us-east-1
    s3:
      url: http://127.0.0.1:4566
      bucket-name: resource
      access-key: localstack
      secret-key: localstack
logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error


spring:
  application:
    name: resource-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:resource}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server.port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka