FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
MAINTAINER Javokhir-tech
COPY target/GatewayService-0.0.1-SNAPSHOT.jar GatewayService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/GatewayService-0.0.1-SNAPSHOT.jar"]