version: '3'

volumes:
  db: {}

services:

  db:
    container_name: microservice_db
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data


  localstack:
    image: localstack/localstack
    ports:
      - "4566-4583:4566-4583"
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - USE_SSL=0
      - AWS_CBOR_DISABLE=1
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ../scripts/aws/buckets.sh:/docker-entrypoint-initaws.d/buckets.sh