FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
MAINTAINER Javokhir-tech
COPY target/DiscoveryService-0.0.1-SNAPSHOT.jar DiscoveryService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/DiscoveryService-0.0.1-SNAPSHOT.jar"]