FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
MAINTAINER Javokhir-tech
COPY target/ResourceProcessor-0.0.1-SNAPSHOT.jar ResourceProcessor-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ResourceProcessor-0.0.1-SNAPSHOT.jar"]