FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
MAINTAINER Javokhir-tech
COPY target/ResourceService-0.0.1-SNAPSHOT.jar ResourceService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ResourceService-0.0.1-SNAPSHOT.jar"]