FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
MAINTAINER Javokhir-tech
COPY target/SongService-0.0.1-SNAPSHOT.jar SongService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/SongService-0.0.1-SNAPSHOT.jar"]