spring:
  application:
    name: gateway-service

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
