FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
MAINTAINER Javokhir-tech
COPY target/StorageService-0.0.1-SNAPSHOT.jar StorageService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/StorageService-0.0.1-SNAPSHOT.jar"]