spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB


spring:
  application:
    name: song-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:song}

server.port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}